#!/bin/python3

import argparse

def generate_subdomains(domain_file, wordlist_file):
    with open(domain_file, 'r') as df:
        domains = [line.strip() for line in df.readlines()]
    
    with open(wordlist_file, 'r') as wf:
        words = [line.strip() for line in wf.readlines()]
    
    for domain in domains:
        for word in words:
            print(f"{word}.{domain}")

def main():
    parser = argparse.ArgumentParser(description="Generate subdomains using a wordlist")
    parser.add_argument('-f', '--file', required=True, help="File containing domains")
    parser.add_argument('-w', '--wordlist', required=True, help="File containing wordlist for subdomains")
    
    args = parser.parse_args()
    
    generate_subdomains(args.file, args.wordlist)

if __name__ == "__main__":
    main()
